### ISSUE TITLE
ValueError: Unexpected attribute BTRFS_SEND_A_FILE_OFFSET

### ISSUE THREAD

**Issue by mio-19** [sysnux/btrfs-snapshots-diff#22]
```

Traceback (most recent call last):
  File "/home/user/@temp/btrfs-snapshots-diff.py", line 441, in <module>
    modified, commands = stream.decode()
                         ^^^^^^^^^^^^^^^
  File "/home/user/@temp/btrfs-snapshots-diff.py", line 322, in decode
    idx2, path = self._tlv_get_string(
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/@temp/btrfs-snapshots-diff.py", line 134, in _tlv_get_string
    raise ValueError('Unexpected attribute %s' % self.send_attrs[attr])
ValueError: Unexpected attribute BTRFS_SEND_A_FILE_OFFSET
```

**Comment by pmorch** [comment]
It is a shame that this does not contain a repro or a version that triggered it.

Line 322 no longer has these contents, and it appears `btrfs-snapshots-diff.py` has not been changed since Jan 14, 2021.

**Comment by rmunn** [comment]
Got this too. Here's a `btrfs send --no-data` file that reproduces the issue. It's a snapshot between a freshly-installed virtual machine just before installing the Claude binary, and just after installing it. (I wanted to see what changes the Claude install process makes). It doesn't contain any personal or sensitive data so I don't mind sharing it with the world.

[snapshot-diff.bin.gz](https://github.com/user-attachments/files/29032529/snapshot-diff.bin.gz)

Running `python btrfs-snapshots-diff.py -f /tmp/snapshot-diff.bin -s` (using commit 2d46612ff63d9ba982e67fe2320e8de60be8ca3a of btrfs-snapshots-diff.py) produces the following traceback (which is not quite identical to the one posted by OP):

```
Traceback (most recent call last):
  File "/home/rmunn/code/ai-jail/btrfs-snapshots-diff/btrfs-snapshots-diff.py", line 653, in <module>
    main()
    ~~~~^^
  File "/home/rmunn/code/ai-jail/btrfs-snapshots-diff/btrfs-snapshots-diff.py", line 620, in main
    commands, paths = stream.decode(bogus=args.bogus)
                      ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/home/rmunn/code/ai-jail/btrfs-snapshots-diff/btrfs-snapshots-diff.py", line 325, in decode
    offset2, path = self._tlv_get_string('BTRFS_SEND_A_PATH', offset)
                    ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rmunn/code/ai-jail/btrfs-snapshots-diff/btrfs-snapshots-diff.py", line 105, in _tlv_get_string
    raise ValueError(f'Unexpected attribute {self.send_attrs[attr]}')
ValueError: Unexpected attribute BTRFS_SEND_A_FILE_OFFSET
```

I'll test PR #25 and see if that fixes the issue.

**Comment by rmunn** [comment]
Confirmed, PR #25 allows me to read the btrfs snapshot file and print out the diffs.
